load('Exp1P1.mat');
plot(V1,Vout,'.'); hold all;
load('Exp1P2.mat');
plot(V1,Vout,'.');
load('Exp1P3.mat');
plot(V1,Vout,'.');
xlabel('V_1 (Volts)');
ylabel('V_{out} (Volts)');
title('Voltage Transfer Characteristic for a Diff Amp');
legend('VTC for V_2 = 2 V','VTC for V_2 = 3 V','VTC for V_2 = 4 V','Location','NorthWest');